### ISSUE TITLE
Screen - 3dpad - HW?

### ISSUE THREAD

**Issue by alexb3d** [libretro-mirrors/beetle-saturn-libretro#13] opened 2016-09-12 20:20 UTC
The size of the smallest screen.
https://yadi.sk/i/VaO5JNX2v5ppg

3d pad does not work. You can not configure.

Are they going to implement Mednafen Saturn HW? ._.

**Comment by hiddenasbestos** [comment] 2017-11-09 18:27
I humbly request that this issue be closed. The first link isn't working so the issue there isn't clear (possibly a duplicate of issue #29?). The second point has been resolved as 3D-Pad does now basically work (with issue #69 available to finished off support). The third point is a question relating to the creation a new project and beyond the scope of this core.

**Closed as completed** 2017-11-09 18:59 UTC
